version: '3'
services:
    banco_dados:
      image: mysql
      container_name: banco_dados
      ports:
          - "3307:3306"
      networks:
        - minha-rede
      environment: 
        - MYSQL_USER=root
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=rooms
    rooms_api:
        build: .
        container_name: roomsapi
        ports:
          - "3000:8080"
        networks:
          - minha-rede
        depends_on:
          - "banco_dados"
networks:
  minha-rede:
    driver: bridge
    
